-- ============================================================
-- ESP32 + Flask + Supabase People Counter
-- Time zone for reporting: Africa/Kigali
-- ============================================================

create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- Devices
-- ------------------------------------------------------------
create table if not exists public.devices (
    id uuid primary key default gen_random_uuid(),
    device_id text not null unique,
    device_name text not null,
    location_name text,
    active boolean not null default true,
    created_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- One row = one valid directional crossing. count_delta is the change in
-- the number of people currently inside: +1 entering, -1 leaving.
-- ------------------------------------------------------------
create table if not exists public.person_events (
    id bigint generated by default as identity primary key,
    device_id text not null references public.devices(device_id),
    event_type text not null check (event_type in ('valid_s1_to_s2', 'valid_s2_to_s1')),
    sensor_sequence text not null default 'S1->S2',
    count_delta integer not null default 1 check (count_delta in (-1, 1)),
    event_time timestamptz not null default now(),
    created_at timestamptz not null default now()
);

-- Apply the widened event contract when upgrading an existing database.
alter table public.person_events
    drop constraint if exists person_events_event_type_check,
    drop constraint if exists person_events_count_delta_check;

alter table public.person_events
    add constraint person_events_event_type_check
        check (event_type in ('valid_s1_to_s2', 'valid_s2_to_s1')),
    add constraint person_events_count_delta_check
        check (count_delta in (-1, 1));

create index if not exists idx_person_events_event_time
    on public.person_events(event_time desc);

create index if not exists idx_person_events_device_time
    on public.person_events(device_id, event_time desc);

-- ------------------------------------------------------------
-- Seed the first device
-- ------------------------------------------------------------
insert into public.devices (device_id, device_name, location_name)
values ('ESP32-COUNTER-01', 'Main Entrance Counter', 'Main Entrance')
on conflict (device_id) do nothing;

-- ------------------------------------------------------------
-- SECURITY
-- Flask uses the server-side service-role/secret key.
-- The browser never talks directly to person_events.
-- Keep RLS enabled so accidental direct exposure is not open.
-- ------------------------------------------------------------
alter table public.devices enable row level security;
alter table public.person_events enable row level security;

revoke all on table public.devices from anon, authenticated;
revoke all on table public.person_events from anon, authenticated;

-- The Flask server uses service_role for inserts and server-side reads.
grant usage on schema public to service_role;
grant all on table public.devices, public.person_events to service_role;
grant usage, select on sequence public.person_events_id_seq to service_role;

-- ------------------------------------------------------------
-- Reporting RPC functions
-- Flask calls these with the server-side Supabase client.
-- All report dates are calculated in Africa/Kigali.
-- ------------------------------------------------------------

-- Return columns changed in this version, so drop old signatures before
-- recreating them. Existing event rows remain untouched.
drop function if exists public.get_counter_summary();
drop function if exists public.get_daily_report(integer);
drop function if exists public.get_weekly_report(integer);
drop function if exists public.get_monthly_report(integer);

create or replace function public.get_counter_summary()
returns table (
    today bigint,
    week bigint,
    month bigint,
    all_time bigint,
    current_inside bigint,
    total_entered bigint,
    total_exited bigint
)
language sql
security definer
set search_path = public
as $$
    with x as (
        select
            count(*) filter (
                where event_time >= date_trunc('day', now() at time zone 'Africa/Kigali')
                  and event_time < date_trunc('day', now() at time zone 'Africa/Kigali') + interval '1 day'
                  and count_delta = 1
            ) as today,
            count(*) filter (
                where event_time >= date_trunc('week', now() at time zone 'Africa/Kigali')
                  and count_delta = 1
            ) as week,
            count(*) filter (
                where event_time >= date_trunc('month', now() at time zone 'Africa/Kigali')
                  and count_delta = 1
            ) as month,
            count(*) filter (where count_delta = 1) as all_time,
            greatest(coalesce(sum(count_delta), 0), 0) as current_inside,
            count(*) filter (where count_delta = 1) as total_entered,
            count(*) filter (where count_delta = -1) as total_exited
        from public.person_events
    )
    select
        today,
        week,
        month,
        all_time,
        current_inside,
        total_entered,
        total_exited
    from x;
$$;

create or replace function public.get_daily_report(p_days integer default 30)
returns table (
    day date,
    entered bigint,
    exited bigint,
    net bigint
)
language sql
security definer
set search_path = public
as $$
    select
        d::date as day,
        count(e.id) filter (where e.count_delta = 1)::bigint as entered,
        count(e.id) filter (where e.count_delta = -1)::bigint as exited,
        coalesce(sum(e.count_delta), 0)::bigint as net
    from generate_series(
        (current_date - greatest(p_days - 1, 0)),
        current_date,
        interval '1 day'
    ) d
    left join public.person_events e
      on (e.event_time at time zone 'Africa/Kigali')::date = d::date
    group by d::date
    order by d::date;
$$;

create or replace function public.get_weekly_report(p_weeks integer default 12)
returns table (
    week_start date,
    entered bigint,
    exited bigint,
    net bigint
)
language sql
security definer
set search_path = public
as $$
    select
        w::date as week_start,
        count(e.id) filter (where e.count_delta = 1)::bigint as entered,
        count(e.id) filter (where e.count_delta = -1)::bigint as exited,
        coalesce(sum(e.count_delta), 0)::bigint as net
    from generate_series(
        date_trunc('week', current_date)::date - ((greatest(p_weeks - 1, 0)) * 7),
        date_trunc('week', current_date)::date,
        interval '7 days'
    ) w
    left join public.person_events e
      on date_trunc('week', (e.event_time at time zone 'Africa/Kigali'))::date = w::date
    group by w::date
    order by w::date;
$$;

create or replace function public.get_monthly_report(p_months integer default 12)
returns table (
    month_start date,
    entered bigint,
    exited bigint,
    net bigint
)
language sql
security definer
set search_path = public
as $$
    select
        m::date as month_start,
        count(e.id) filter (where e.count_delta = 1)::bigint as entered,
        count(e.id) filter (where e.count_delta = -1)::bigint as exited,
        coalesce(sum(e.count_delta), 0)::bigint as net
    from generate_series(
        date_trunc('month', current_date)::date - ((greatest(p_months - 1, 0)) * interval '1 month'),
        date_trunc('month', current_date)::date,
        interval '1 month'
    ) m
    left join public.person_events e
      on date_trunc('month', (e.event_time at time zone 'Africa/Kigali'))::date = m::date
    group by m::date
    order by m::date;
$$;

-- Only the server-side service role should call these functions.
revoke execute on function public.get_counter_summary() from public, anon, authenticated;
revoke execute on function public.get_daily_report(integer) from public, anon, authenticated;
revoke execute on function public.get_weekly_report(integer) from public, anon, authenticated;
revoke execute on function public.get_monthly_report(integer) from public, anon, authenticated;

grant execute on function public.get_counter_summary() to service_role;
grant execute on function public.get_daily_report(integer) to service_role;
grant execute on function public.get_weekly_report(integer) to service_role;
grant execute on function public.get_monthly_report(integer) to service_role;
